### ISSUE TITLE
System.ArgumentNullException

### ISSUE THREAD

**Issue by NinjaCross** [philips-software/roslyn-analyzers#121]
Today, for the first time I encountered this exception while building a .NET CORE 3.1 solution using version 1.1.4

```
CSC : warning AD0001: Analyzer 'Philips.CodeAnalysis.DuplicateCodeAnalyzer.AvoidDuplicateCodeAnalyzer' threw an exception of type 'System.ArgumentNullException' with message 'Value cannot be null.
```

Unfortunately I don't have more details to provide

**Comment by NinjaCross** [comment]
Any news about this ?

**Comment by bcollamore** [comment]
Unfortunately not.  We have not seen a repro of this yet.  (We do have a large code base that these analyzers run on; typically, when something like this happens, we repro it quickly.  So this is unusual.)  Is it reproducible on your side?

**Comment by NinjaCross** [comment]
The problem manifests itself in a pseudo-random fashion.
It happens to my team several times a day, but the error message is always the same, so I don't have any more details to provide.

**Comment by bcollamore** [comment]
OK.  Is it fair to assume that this started after updating the version recently?

**Comment by NinjaCross** [comment]
I couldn't say.
I used this analyzer just for a couple of hours before the latest fix, so I don't know if the error happened also with the previous release

**Comment by NinjaCross** [comment]
@bcollamore any news ?

**Comment by NinjaCross** [comment]
@bcollamore are there news about this topic ?

**Comment by bcollamore** [comment]
Hi @NinjaCross, the ms roslyn repo shows multiple issues concerning people looking for more detailed information (ie call stacks), but it has not been implemented. So I implemented it in a custom way in v1.1.6.  It will not give me line numbers (because PDBs are not included), but it may narrow down the location of the problem.  Perhaps give this version a try when it is convenient to do so.

**Comment by NinjaCross** [comment]
@bcollamore thank you for your effort, I will absolutely give a try to the new release !

**Comment by NinjaCross** [comment]
The problem never occurred again during the last weeks, so I'm going to close the issue. 
Thanks @bcollamore for your help.
