### ISSUE TITLE
No CodeFix available for Philips.CodeAnalysis.DuplicateCodeAnalyzer

### ISSUE THREAD

**Issue by NinjaCross** [philips-software/roslyn-analyzers#129]
Citation from https://github.com/philips-software/roslyn-analyzers/blob/master/Philips.CodeAnalysis.DuplicateCodeAnalyzer/Philips.CodeAnalysis.DuplicateCodeAnalyzer.md 

` Use the provided Code Fixer to automatically add violations to the whitelist.`

Unfortunately, no code fix appear to be available anywhere in the IDE (either VS 2022 and Rider).
I clicked and looked everywhere, but I wasn't able to find any code fix available.
It's not a big problem, but since there are no examples on the expected syntax to use in the  `DuplicateCode.Allowed.txt`, I have no idea to how specify exceptions manually.

Could you please provide a sample for `DuplicateCode.Allowed.txt` and/or a fix for the "code fix" function not appearing in the IDE ?

Thank you very much

**Comment by NinjaCross** [comment]
@bcollamore could you please give a feedback on how to add a manual exception on `DuplicateCode.Allowed.txt` ?
Thankyou very much.

**Comment by bcollamore** [comment]
@NinjaCross Let me know if this image helps. If so, I'll formally document it for future reference.
![image](https://user-images.githubusercontent.com/57269455/159707547-d357728b-d6ec-4641-b8a2-f48aad82f215.png)
Essentially,
1. Add the DuplicateCode.Allowed.txt file to the project
2. Set the Properties to "C# Analyzer additional file".  (Pre VS2022, I believe it was called "Additional File.) (Generically speaking, analyzers have access to files tagged as such.  This step is typically the magic that is required/missing.)
3. 1 line per method name to ignore.
4. Perhaps(?) re-open the project the first time that file is created - I'm not sure. One does not need to restart anything based on edits to the file.

**Comment by ynsehoornenborg** [comment]
@bcollamore Maybe we should switch to a format like Microsoft's Banned API Analyzers are using, see: [BannedApiAnalyzers.Help.md](https://github.com/dotnet/roslyn-analyzers/blob/main/src/Microsoft.CodeAnalysis.BannedApiAnalyzers/BannedApiAnalyzers.Help.md)

This format takes namespaces, generics and overloads into account.

**Comment by NinjaCross** [comment]
Hi. Are there any news about this ?

**Comment by ynsehoornenborg** [comment]
I have worked on this, but nothing working fully yet.
We did identify the requirement to make the file format backward compatible, in other words to support the old format next to the new.

**Comment by NinjaCross** [comment]
> I have worked on this, but nothing working fully yet. We did identify the requirement to make the file format backward compatible, in other words to support the old format next to the new. This made the implementation taker a bit longer than expected.

Thankyou very much @ynsehoornenborg for your feedback.
When can we expect to see a new NuGet package containing this improvement ?
I'm very eager to test it :)
