### ISSUE TITLE
PH2069 "Don't call string.Format unnecessarily" should not complain if the method actually expects a FormattableString

### ISSUE THREAD

**Issue by genxs-trading** [philips-software/roslyn-analyzers#134]
`
void Blah(FormattableString s) {
}

void Main() {
   int blah = 10;
  Blah($"{blah}");  // <-- should not trigger PH2069
}
`

**Comment by ynsehoornenborg** [comment]
I'm unable to reproduce this issue on latest version (1.2.29).

Please note that if you have an overloaded method with a `string` argument, that takes precedence over the FormattableString. Same holds for Extension method. In your code example, if there is a method `void Blah(string s) {...}` dotnet will call that one (and our Analyzer warns you accordingly). Might this be the case for you @genxs-trading ?

Nevertheless, raised PR #148 to add your code example as an explicit test case.

**Comment by ynsehoornenborg** [comment]
After some experimentation, I have indeed found a scenario where there a false positive of PH2069 is popping up. 

To prevent this false positive, we have pushed version [1.2.30](https://www.nuget.org/packages/Philips.CodeAnalysis.MaintainabilityAnalyzers/1.2.30) to nuget.
