### ISSUE TITLE
Avoid checking structs for null

### ISSUE THREAD

**Issue by bcollamore** [philips-software/roslyn-analyzers#161]
I believe I've seen this in a popular 3rd party analyzer package already somewhere. Consider enabling it on our project, and/or creating the analyzer if unavailable elsewhere.

_Originally posted by @ynsehoornenborg in https://github.com/philips-software/roslyn-analyzers/pull/159#discussion_r1045446653_

**Comment by ynsehoornenborg** [comment]
this is already checked by the compiler:
```
int i = 0;
if (i == null) {
```
will throw a compiler error: `error CS0472: The result of the expression is always 'false' since a value of type 'int' is never equal to 'null' of type 'int?'`
