### ISSUE TITLE
Every Linq statement on a separate line for readability

### ISSUE THREAD

**Issue by bcollamore** [philips-software/roslyn-analyzers#162]
Is there a popular 3rd party analyzer package to auto-enforce this everywhere? Or, create?

_Originally posted by @ynsehoornenborg in https://github.com/philips-software/roslyn-analyzers/pull/159#discussion_r1045451380_

**Comment by ynsehoornenborg** [comment]
Can't find it in StyleCop or ReSharper. So, seems something worth adding. And doesn't seem to be particular difficult to implement.

**Comment by ynsehoornenborg** [comment]
Be aware of the two types of Linq syntax:
``` cs
customers
  .Where(c => c.IsActive)
  .Select(a => a.ID)
```
versus
``` cs
from cust in customers
where cust.IsActive
select cust.ID;
```
