### ISSUE TITLE
Avoid multiple conditions in same line for readability

### ISSUE THREAD

**Issue by bcollamore** [philips-software/roslyn-analyzers#165]
Investigate 3rd party analyzer or create.

Consider putting each condition on its own line for readability

_Originally posted by @ynsehoornenborg in https://github.com/philips-software/roslyn-analyzers/pull/159#discussion_r1045453437_

**Comment by ynsehoornenborg** [comment]
Expected StyleCop to have such a rule, but didn't found it.

To implement this we should check that in an `if` or `?` condition, each `&&` or `||` operand is immediately followed by an `EndOfLineTrivia`.
