### ISSUE TITLE
AvoidInvocationAsArgument: Support lambda expressions

### ISSUE THREAD

**Issue by bcollamore** [philips-software/roslyn-analyzers#187]
Could we support Lambda expressions in a future version, if so, please create an Issue for it (or keep this one open)

_Originally posted by @ynsehoornenborg in https://github.com/philips-software/roslyn-analyzers/pull/177#discussion_r1059853582_

**Comment by ynsehoornenborg** [comment]
I'm not so sure if this is a good idea to write an Analyzer for.
It would mean that the following, perfectly normal LINQ cocde, will raise a diagnostics:
```cs
haystack.FirstOrDefault(item => item.Id == needle);
```

**Comment by ynsehoornenborg** [comment]
To much discussion on how to shape this with LINQ code in mind, closing this issue for now.
