### ISSUE TITLE
Not reproducable dogfood failure

### ISSUE THREAD

**Issue by ynsehoornenborg** [philips-software/roslyn-analyzers#296]
The following error is reported by DogFood ci job:
``` txt
Error: /home/runner/work/roslyn-analyzers/roslyn-analyzers/Philips.CodeAnalysis.Common/AllowedSymbols.cs(100,5): 
error PH2120: Document the fact that this method can potentially throw an exception of type InvalidDataException.
```

However, the [test case](https://github.com/philips-software/roslyn-analyzers/blob/ba775593b7d4c475f76defebdc533442183a9e30/Philips.CodeAnalysis.Test/Maintainability/Documentation/DocumentThrownExceptionsAnalyzerTest.cs#L100) that should guard this exact same scenario passes.

**Comment by bcollamore** [comment]
This is the issue: https://github.com/dotnet/roslyn/issues/58210
