### ISSUE TITLE
Idea: pair on implementing an analyzer pointing out overly specific function parameters

### ISSUE THREAD

**Issue by kryptt** [philips-software/roslyn-analyzers#58]
It would be interesting to start a (set of) analyzer(s) that can detect when a function parameter is more specific than necessary by looking up its tree, or identifying contextual bounds that can reduce the state space for that function. 

Along the lines of this article: https://medium.com/swlh/type-system-saving-55db2ca062ff

I can try to come up with a pull request for this if it makes sense here

**Comment by bcollamore** [comment]
If I understand you correctly, yes, Roslyn can be a good technology for identifying these types of situations.  Is what you are describing along the lines of https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1011?view=vs-2019?  There are presumably plenty of interesting permutations here.

**Comment by kryptt** [comment]
Yes, exactly, also the implementation for CA1011 can be a great starting point. 
There are a couple of other ones that are interesting along these same lines: 

1. In the case of Ints or String parameters, if only 3 values are ever used we can suggest the use of an enum. 
2. In the case of methods that is overloaded with types that don't share a hierarchy we can suggest to create an interface.
3. We can create a warning for types that have null fields

Do you believe these would be useful, are they already in your radar?

**Comment by bcollamore** [comment]
I am not aware of specific plans for these.  Let's try moving this conversation to the new Discussions feature, and subsequently creating individuals Issues as worthy.

**Comment by bcollamore** [comment]
https://github.com/philips-software/roslyn-analyzers/discussions/61
