### ISSUE TITLE
PH2125 "Align + with ==" conflicts with CA1046

### ISSUE THREAD

**Issue by bcollamore** [philips-software/roslyn-analyzers#685]
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1046
found on version 1.2.32

**Comment by ynsehoornenborg** [comment]
The documentation of CA1046 states:
```
If it is meaningful to do addition or subtraction on instances of the type,
it is probably correct to implement the equality operator and suppress the violation.
```
This seems to be in-line with PH2125.

Any opinions ?

**Comment by bcollamore** [comment]
Yes @ynsehoornenborg, I agree. You are correct.
