### ISSUE TITLE
DocumentUnhandledExceptionsAnalyzer throws exception

### ISSUE THREAD

**Issue by bcollamore** [philips-software/roslyn-analyzers#705]
25>CSC : error AD0001: Analyzer 'Philips.CodeAnalysis.MaintainabilityAnalyzers.Documentation.DocumentUnhandledExceptionsAnalyzer' threw an exception of type 'System.IO.FileNotFoundException' with message 'Could not load file or assembly 'Mono.Cecil, Version=0.11.4.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e' or one of its dependencies. The system cannot find the file specified.'.

**Comment by bcollamore** [comment]
That's correct. To trigger the error I blindly enabled the analyzer on a large legacy codebase. I can investigate details if desired.

**Comment by ynsehoornenborg** [comment]
Well, this is the user scenario we aim to support, so it should _just work_. I'll have a crack at a local codebase, see if I can reproduce it easily.
