### ISSUE TITLE
PH2082 Unexpected error message on string variable

### ISSUE THREAD

**Issue by mayerj** [philips-software/roslyn-analyzers#74]
@ynsehoornenborg I am curious if this is intended behavior?  (I added the analyzers to the analyzer project to generate this).

If this is expected, what is the suggested fix?

![image](https://user-images.githubusercontent.com/4032461/113177660-c44bb400-921b-11eb-814d-3877c7192822.png)

**Comment by ynsehoornenborg** [comment]
In this case, the name of the option forces you into confusing naming. But I still feel you could improve here.

In retospect, I would call this option exceptions_suppressions_file. Let's assume this cannot be (easily) changed. The name of your variable however, in under your control.

As with the SuppressMessage of FxCop. For humans the code:
if (!suppressException(myException))
is more readable then:
if (!ignoreException(myException))

Hence my suggestion would be to rename to something that includes suppression.

**Comment by ynsehoornenborg** [comment]
I do feel however, we could improve on the description. As its scope is broader then just boolean types.

**Comment by bcollamore** [comment]
Let's update the title of the analyzer to note the broadened scope.  (When I rolled out the analyzer, the findings on the booleans were generally gold.  The findings on the non-booleans felt like false positives, but my mindset was in "deploy" mode, not "refactor" mode.  So maybe when it trips during new development it would be interesting.  It also felt a little unnatural in Unit Tests, where the author is often explicitly trying to test the negative case.)

**Comment by ynsehoornenborg** [comment]
The unit test case is something we could consider to exclude from Analysis for this analyzer. Not sure how I can reliably identify that in the Maintainability assembly, suggestions welcome.

BTW: The name of the analyzer is PositiveNamingAnalyzer, which addresses its scope correctly. However, the description text does not. I'll improve that text.

**Comment by bcollamore** [comment]
See Helper.IsTestClass
